#!/bin/bash

alias bash='bash --rcfile "$BASH_ENV"'
alias ls='ls --color=auto'
alias la='ls -a'
alias lA='ls -A'
alias ll='ls -lh'
alias lla='ls -lAh'
alias llt='ls -lhrt'
alias lt='ls -rt'
alias els='exa'
alias ell='exa -l'
alias ela='exa -a'
alias ella='exa -la'
alias elt='exa -s time'
alias ellt='exa -ls time'
alias diff='diff -u --color=auto'
alias grep='grep --color=auto'
alias ip='ip --color=auto'
alias less='less -r'
alias src='. ~/.bash_profile'
alias kms='sudo shutdown now'
alias vc='vimcat'
alias hi='highlight --out-format truecolor'
alias e="$EDITOR -p"
alias psuf="ps -u $USER f"
alias pi=pacinstall
alias nvim-qt='nvim-qt --no-ext-tabline --no-ext-popupmenu'
alias findf='find -name'
alias finf='findf'
# these are hardcoded personal locations for my windows drive
alias mwin='sudo mount /dev/nvme1n1p3 /mnt/win'
alias umwin='sudo umount /mnt/win'
alias p=pacman
alias brep=bgrep
alias ungron='gron --ungron'
# uses a path set in the bashrc
alias schwrk="pushd $SCHWRK"
alias scripts='pushd ~/.local/bin/scripts'
alias eagle="QT_XCB_GL_INTEGRATION=xcb_egl eagle"
alias se=dmenuedit
alias gssh='eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519'
alias lf=lfrun
# nv points to my dev version of nvim, nvim points to the stable one in the repos
alias nv='/usr/local/bin/nvim -p'
alias nvim='/usr/bin/nvim'
alias config-git='command git --git-dir=$HOME/gitstuffs/configs --work-tree=$HOME'
alias confg=config-git
alias sys-config-git='command git --git-dir=$HOME/gitstuffs/sys-configs --work-tree=/'
alias sconfg=sys-config-git
alias pd=pushd
alias pod=popd
alias gdl='pushd ~/Downloads'
